openapi: 3.0.1
info:
  title: monster-chain-devil
  x-cortex-tag: monster-chain-devil
  x-cortex-custom-metadata:
    alignment: lawful-evil
    type: fiend
    challenge_rating: 8
    legendary: false
    source: dnd-5e
  x-cortex-type: monster
